---
# tasks file for mysql

- name: Optimize the Operation System parameters
  shell: |
    
    echo never > /sys/kernel/mm/transparent_hugepage/enabled
    echo never > /sys/kernel/mm/transparent_hugepage/defrag
    echo 0 > /proc/sys/kernel/numa_balancing
    echo 0 > /proc/sys/vm/zone_reclaim_mode
    
    blockdev --setra 64 {{ device }}
