---
# tasks file for mysql

- name: Modify the root user password
  mysql_user:
    login_user: root
    login_unix_socket: "{{ mysql_dir }}/my3306/run/mysql.sock"
    login_port: 3306
    name: root
    password: 123456
    host: "%"
    priv: '*.*:ALL'
    state: present

- name: Create database sysbench
  mysql_db:
    login_host: "{{ mysql_host }}"
    login_password: 123456
    login_port: 3306
    login_user: root
    state: present
    name: tpcc1000
 
- name: import create table sql
  mysql_db:
    login_host: "{{ mysql_host }}"
    login_password: 123456
    login_port: 3306
    login_user: root
    state: import
    name: tpcc1000
    target: {{ item.sql }}
    with_items:
      - {{ sql: '{{ root_dir }}/tpcc/create_table.sql' }}
      - {{ sql: '{{ root_dir }}/tpcc/add_fkey_idx.sql' }}
      
- name: load the test data
  shell: |
    ./tpcc_load -h {{ mysql_host }} -d tpcc1000 -u root -p "123456" -w 50
  args:
    chdir: "{{ root_dir }}/tpcc"
  environment:
    PATH: "{{ mysql_dir }}/my3306/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "{{ mysql_dir }}/my3306/lib:{{ ansible_env.LD_LIBRARY_PATH }}"

